version: "3.8"
services: 
  web:
    container_name: imogoat
    build: .
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000