import "./global.css";
import { AuthProvider } from "@/context/AuthContext";
import LayoutWrapper from "@/components/LayoutWrapper";

export const metadata = {
  title: "ImoGOAT",
  description: "Generated by Next.js",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/favicon.png?v=4"],
    shortcut: ["/favicon.png"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
