import "./global.css"
import Header from "../components/layout/Header"
import Footer from "@/components/layout/Footer"

export const metadata = {
  title: 'ImoGOAT',
  description: 'Generated by Next.js',
  icons:{
    icon:['/favicon.ico?v=4'],
    apple:['/favicon.png?v=4'],
    shortcut:['/favicon.png']
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="m-auto min-h-[500px] sm:w-11/12 w-97p">
          <div>
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  )
}
